[package]
name = "cryptons_gen"
version = "0.0.2"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = "2.33.3"
rayon = "1.5.1"
bitcoin = "0.27.0"
getrandom = "0.2.2"
secp256k1 = "0.20.3"
